# Google Cloud Build configuration for clockit_api
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clockit-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/clockit-api:latest'
      - '-f'
      - 'clockit_api/Dockerfile'
      - 'clockit_api'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clockit-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/clockit-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        REDIS_URL="${_REDIS_URL}"
        FIREBASE_B64="${_FIREBASE_SERVICE_ACCOUNT_B64}"
        API_BASE_URL="${_API_BASE_URL}"
        ALLOWED_ORIGINS="${_ALLOWED_ORIGINS}"
        RATE_LIMIT_WINDOW_MS="${_RATE_LIMIT_WINDOW_MS}"
        RATE_LIMIT_MAX_REQUESTS="${_RATE_LIMIT_MAX_REQUESTS}"
        LOG_LEVEL="${_LOG_LEVEL}"
        ENABLE_ADMIN_SETUP="${_ENABLE_ADMIN_SETUP}"
        ADMIN_SETUP_TOKEN="${_ADMIN_SETUP_TOKEN}"
        INITIAL_ADMIN_EMAILS="${_INITIAL_ADMIN_EMAILS}"
        if [ -z "$LOG_LEVEL" ]; then LOG_LEVEL="info"; fi
        if [ -z "$ENABLE_ADMIN_SETUP" ]; then ENABLE_ADMIN_SETUP="false"; fi
        ENV_VARS="NODE_ENV=production,PORT=8080"
        if [ -n "$REDIS_URL" ]; then
          ENV_VARS="$ENV_VARS,REDIS_URL=$REDIS_URL"
        fi
        if [ -n "$FIREBASE_B64" ]; then
          ENV_VARS="$ENV_VARS,FIREBASE_SERVICE_ACCOUNT_B64=$FIREBASE_B64"
        fi
        if [ -n "$API_BASE_URL" ]; then
          ENV_VARS="$ENV_VARS,API_BASE_URL=$API_BASE_URL"
        fi
        if [ -n "$ALLOWED_ORIGINS" ]; then
          ENV_VARS="$ENV_VARS,ALLOWED_ORIGINS=$ALLOWED_ORIGINS"
        fi
        if [ -n "$RATE_LIMIT_WINDOW_MS" ]; then
          ENV_VARS="$ENV_VARS,RATE_LIMIT_WINDOW_MS=$RATE_LIMIT_WINDOW_MS"
        fi
        if [ -n "$RATE_LIMIT_MAX_REQUESTS" ]; then
          ENV_VARS="$ENV_VARS,RATE_LIMIT_MAX_REQUESTS=$RATE_LIMIT_MAX_REQUESTS"
        fi
        if [ -n "$LOG_LEVEL" ]; then
          ENV_VARS="$ENV_VARS,LOG_LEVEL=$LOG_LEVEL"
        fi
        if [ -n "$ENABLE_ADMIN_SETUP" ]; then
          ENV_VARS="$ENV_VARS,ENABLE_ADMIN_SETUP=$ENABLE_ADMIN_SETUP"
        fi
        if [ -n "$ADMIN_SETUP_TOKEN" ]; then
          ENV_VARS="$ENV_VARS,ADMIN_SETUP_TOKEN=$ADMIN_SETUP_TOKEN"
        fi
        if [ -n "$INITIAL_ADMIN_EMAILS" ]; then
          ENV_VARS="$ENV_VARS,INITIAL_ADMIN_EMAILS=$INITIAL_ADMIN_EMAILS"
        fi

        gcloud run deploy clockit-api \
          --image "gcr.io/$PROJECT_ID/clockit-api:$COMMIT_SHA" \
          --region "europe-west4" \
          --platform "managed" \
          --allow-unauthenticated \
          --set-env-vars "$ENV_VARS" \
          --max-instances "10" \
          --min-instances "0" \
          --memory "512Mi" \
          --cpu "1" \
          --timeout "300s"

images:
  - 'gcr.io/$PROJECT_ID/clockit-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/clockit-api:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
