export const COLLECTIONS = {
  USERS: 'Users',
  API_TOKENS: 'ApiTokens',
  GOALS: 'Goals',
  SESSIONS: 'Sessions',
  UPLOADS: 'Uploads',
  FEATURE_ENTITLEMENTS: 'FeatureEntitlements',
  GOAL_GROUPS: 'GoalGroups',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export const TOKEN_PREFIX = 'clockit_';
export const TOKEN_LAST_FOUR_LENGTH = 4;
